"""Self-play card-play environment for training the RL agent.

Deliberately simplified scope, matching what's actually tractable to train
from scratch in this project (see `docs/rl_training.md` for the full
reasoning):

  - Bidding is skipped entirely. Each self-play game starts from a random
    52-card deal with a randomly chosen declarer and strain (uniformly
    over C/D/H/S/NT). The RL agent only ever has to learn CARD PLAY, never
    bidding — bidding stays exactly the existing rules-based engine in
    `bidding/`, per the project's scope.
  - Every seat is controlled by the same shared network (that's what makes
    it self-play): the network is fed full information (every hand's
    remaining cards) during training, because a self-play game is a fully
    determined world — there's no hidden information *within* one
    self-play game, only when the trained network is later used for real,
    imperfect-information play (see `rl/rl_player.py`, which wraps it with
    PIMC sampling for exactly that reason).
  - The reward signal is simple and terminal: every decision a seat makes
    is credited with "how many of the 13 tricks did my side end up
    with" — the whole game's outcome, not a per-trick shaped reward. This
    is a standard, if basic, REINFORCE setup: high-variance but unbiased,
    and the value head (trained as a baseline) reduces that variance.

Nowhere does this touch the uploaded bridge book — training data is
entirely self-generated by dealing random hands and playing them out.

Opponent diversity (`heuristic_side` below): pure self-play has a known
failure mode — the network only ever plays against copies of itself, so
it can converge to a policy that's well-adapted to its OWN quirks without
generalizing to an opponent with a genuinely different style. Concretely,
this project measured exactly that gap: a checkpoint trained by pure
self-play scored *worse* as declarer against the rule-based heuristic bot
than the heuristic bot scored against itself (see docs/rl_training.md),
even though the same checkpoint looked fine by its own self-play metrics.
`play_game(..., heuristic_side=...)` lets a training run mix in games
where one side is played by the heuristic bot instead of the network, so
the network is forced to learn to handle a genuinely different opponent
style, not just outplay its own mirror image. Only the network's own
decisions are ever recorded for training (the heuristic bot's moves are
just part of the environment it's reacting to) — no importance sampling
needed, since we're not trying to learn anything from the heuristic
bot's choices, only from how the network responds to them.
"""
from __future__ import annotations

import random
from dataclasses import dataclass
from typing import List, Optional, Tuple

import numpy as np

from engine.deal import Hand, Suit, deal_random
from bidding.calls import SEATS, partner_of
from cardplay.trick_engine import PlayState
from cardplay.bot_player import choose_card as heuristic_choose_card
from rl import features
from rl.network import PolicyValueNet

STRAINS = ["C", "D", "H", "S", "NT"]


@dataclass
class Decision:
    seat: str
    x: np.ndarray
    mask: np.ndarray
    action: int
    side: str  # "NS" or "EW" — whose side made this decision
    trick_index: int  # 0-based: which of the 13 tricks this decision was made during


@dataclass
class GameOutcome:
    decisions: List[Decision]
    tricks: dict  # {"NS": int, "EW": int} — final trick counts, for logging/display
    completed_tricks: list  # the 13 real Trick objects, in order — used to compute per-trick rewards
    trump: object  # Optional[Suit] — needed to determine each trick's winner


def _random_contract(rng: random.Random) -> Tuple[str, str, str]:
    declarer = rng.choice(SEATS)
    strain = rng.choice(STRAINS)
    dealer = declarer
    return declarer, strain, dealer


def play_game(
    net: PolicyValueNet,
    py_rng: random.Random,
    np_rng: np.random.Generator,
    heuristic_side: Optional[str] = None,
    greedy: bool = False,
) -> GameOutcome:
    """Play one full-information game. `heuristic_side` is None (pure
    self-play: the network plays every seat, as before), "NS", or "EW" —
    when given, that side is played by the heuristic bot instead of the
    network, and its decisions are simply not recorded (see module
    docstring for why this exists and why it's safe not to importance-
    sample them)."""
    declarer, strain, dealer = _random_contract(py_rng)
    deal = deal_random(dealer=dealer, seed=py_rng.randrange(1 << 30))
    trump = None if strain == "NT" else Suit(strain)
    hands = {s: list(deal.hands[s].cards) for s in SEATS}
    play_state = PlayState(hands=hands, declarer=declarer, strain=strain, trump=trump, dealer=dealer)

    decisions: List[Decision] = []
    while not play_state.is_complete():
        seat = play_state.next_to_play
        side = "NS" if seat in ("N", "S") else "EW"
        trick_index = len(play_state.completed_tricks)

        if side == heuristic_side:
            card = heuristic_choose_card(seat, play_state, seed=py_rng.randrange(1 << 30))
        else:
            x = features.encode(seat, play_state)
            mask = features.legal_mask(seat, play_state)
            action = net.act(x, mask, np_rng, greedy=greedy)
            decisions.append(Decision(seat=seat, x=x, mask=mask, action=action, side=side, trick_index=trick_index))
            card = features.card_for_index(action)

        play_state.play_card(seat, card)

    tricks = play_state.tricks_by_side()
    return GameOutcome(decisions=decisions, tricks=tricks, completed_tricks=list(play_state.completed_tricks), trump=play_state.trump)


def play_self_play_game(
    net: PolicyValueNet,
    py_rng: random.Random,
    np_rng: np.random.Generator,
    greedy: bool = False,
) -> GameOutcome:
    """Pure self-play — every seat played by the network. Kept as its own
    name (rather than requiring callers to pass `heuristic_side=None`
    everywhere) since this was the original training mode and is still
    the right choice for, e.g., quick sanity tests."""
    return play_game(net, py_rng, np_rng, heuristic_side=None, greedy=greedy)


def decisions_to_training_batch(outcome: GameOutcome) -> List[Tuple[np.ndarray, np.ndarray, int, float]]:
    """Credit each decision with its side's *return-to-go* — how many of
    the REMAINING tricks (from this decision's own trick onward) that
    side ends up winning — rather than the final trick count for the
    whole game repeated at every decision.

    This project's first version used the plain final total for every
    decision, which is the mathematically correct return-to-go for a
    reward given *only* at the very end (a purely terminal reward: since
    nothing is earned before the last step, the sum of future rewards
    from any point is just that one final number). It's also a genuinely
    hard credit-assignment problem for REINFORCE: a decision made in
    trick 2 and a decision made in trick 12 get the exact same training
    signal, even though they're very different in how much they could
    possibly still affect the outcome — and in practice, training with
    that formulation plateaued early (see docs/rl_training.md) instead of
    improving.

    Decomposing the total into its natural per-trick components fixes
    this without changing what's being estimated: `tricks won by side S`
    is exactly the sum, over all 13 tricks, of "did S win this trick"
    (0 or 1) — a well-known decomposition (the same total, attributed to
    the specific tricks that earned it) rather than a different quantity.
    A decision made during trick k is credited with the sum of those
    per-trick indicators from trick k onward: still S's eventual trick
    count if k=0 (matching the old behavior exactly for the very first
    decisions), but a much smaller, much more specific number for a
    decision made late in the hand — shrinking the variance of the
    training signal for exactly the decisions that most need it.
    """
    n_tricks = len(outcome.completed_tricks)
    per_trick_winning_side = [
        "NS" if trick.winner(outcome.trump) in ("N", "S") else "EW"
        for trick in outcome.completed_tricks
    ]

    # Suffix sums: return_to_go[side][i] = tricks `side` wins from trick i
    # onward (inclusive). Built backward so each entry is O(1) to compute.
    return_to_go = {"NS": [0] * n_tricks, "EW": [0] * n_tricks}
    running = {"NS": 0, "EW": 0}
    for i in range(n_tricks - 1, -1, -1):
        running[per_trick_winning_side[i]] += 1
        return_to_go["NS"][i] = running["NS"]
        return_to_go["EW"][i] = running["EW"]

    batch = []
    for d in outcome.decisions:
        ret = float(return_to_go[d.side][d.trick_index])
        batch.append((d.x, d.mask, d.action, ret))
    return batch
