"""Self-play training loop for the card-play RL agent.

Run it directly:

    python -m rl.train --iterations 200 --games-per-iter 20 --out rl/checkpoints/latest.pt

See `docs/rl_training.md` for what this is actually doing, how long it
takes, and how to evaluate a checkpoint once you have one — that doc is
written for you (the user), not just as code comments, since you'll want
to be able to explain this training process yourself.

All training data is generated by self-play (random deals dealt by
`engine/deal.py`, played out by the network against itself) — nothing here
ever reads the uploaded bridge book or any other copyrighted material.
"""
from __future__ import annotations

import argparse
import os
import random
import time

import numpy as np
import torch

from rl.env import play_game, decisions_to_training_batch
from rl.network import PolicyValueNet, get_device


def train(
    iterations: int,
    games_per_iter: int,
    lr: float,
    seed: int,
    out_path: str,
    resume_from: str | None,
    eval_every: int,
    eval_games: int,
    device: str | None = None,
    heuristic_opponent_prob: float = 0.0,
) -> PolicyValueNet:
    py_rng = random.Random(seed)
    np_rng = np.random.default_rng(seed)

    net = (
        PolicyValueNet.load(resume_from, device=device)
        if resume_from
        else PolicyValueNet(seed=seed, device=device)
    )
    print(f"Training on device: {net.device}  (torch.cuda.is_available() = {torch.cuda.is_available()})")
    if heuristic_opponent_prob > 0:
        print(
            f"Opponent diversity: {heuristic_opponent_prob:.0%} of games have one randomly "
            f"chosen side played by the heuristic bot instead of self-play, so the network "
            f"has to learn to handle a real, different playing style rather than only its "
            f"own mirror image (see rl/env.py's module docstring)."
        )

    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)

    for it in range(1, iterations + 1):
        t0 = time.time()
        batch = []
        declarer_tricks = []
        for _ in range(games_per_iter):
            heuristic_side = None
            if heuristic_opponent_prob > 0 and py_rng.random() < heuristic_opponent_prob:
                heuristic_side = py_rng.choice(["NS", "EW"])
            outcome = play_game(net, py_rng, np_rng, heuristic_side=heuristic_side, greedy=False)
            batch.extend(decisions_to_training_batch(outcome))
            declarer_tricks.append(max(outcome.tricks.values()))

        stats = net.train_step(batch, lr=lr)
        elapsed = time.time() - t0

        print(
            f"iter {it:4d}/{iterations}  games={games_per_iter}  "
            f"decisions={len(batch):4d}  policy_loss={stats['policy_loss']:.3f}  "
            f"value_loss={stats['value_loss']:.3f}  avg_top_side_tricks={np.mean(declarer_tricks):.2f}  "
            f"({elapsed:.1f}s)"
        )

        if eval_every and it % eval_every == 0:
            from rl.evaluate import evaluate_vs_heuristic

            result = evaluate_vs_heuristic(net, num_deals=eval_games, seed=seed + it)
            print(
                f"  [eval] RL-as-declarer avg tricks: {result['rl_declarer_avg_tricks']:.2f}  "
                f"heuristic-as-declarer avg tricks: {result['heuristic_declarer_avg_tricks']:.2f}  "
                f"(same {eval_games} deals, both ways)"
            )

        net.save(out_path)

    print(f"Saved final checkpoint to {out_path}")
    return net


def main() -> None:
    parser = argparse.ArgumentParser(description="Train the self-play card-play RL agent.")
    parser.add_argument("--iterations", type=int, default=200)
    parser.add_argument("--games-per-iter", type=int, default=20)
    parser.add_argument("--lr", type=float, default=3e-4)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--out", type=str, default="rl/checkpoints/latest.pt")
    parser.add_argument("--resume-from", type=str, default=None)
    parser.add_argument("--eval-every", type=int, default=20)
    parser.add_argument("--eval-games", type=int, default=30)
    parser.add_argument(
        "--device",
        type=str,
        default=None,
        choices=["cuda", "cpu"],
        help="Force a device; default auto-picks CUDA if available, else CPU.",
    )
    parser.add_argument(
        "--heuristic-opponent-prob",
        type=float,
        default=0.0,
        help=(
            "Probability that a given game has one randomly chosen side (NS or EW) played by "
            "the heuristic bot instead of self-play, to fix the self-play generalization gap "
            "(see rl/env.py's module docstring and docs/rl_training.md). 0.0 = pure self-play "
            "(the original behavior); try 0.5 for a genuine mix."
        ),
    )
    args = parser.parse_args()

    train(
        iterations=args.iterations,
        games_per_iter=args.games_per_iter,
        lr=args.lr,
        seed=args.seed,
        out_path=args.out,
        resume_from=args.resume_from,
        eval_every=args.eval_every,
        eval_games=args.eval_games,
        device=args.device,
        heuristic_opponent_prob=args.heuristic_opponent_prob,
    )


if __name__ == "__main__":
    main()
